import importlib
import json
import sys

# Argument 1: Denotes whether this is a grading or generating API script
# Argument 2: Downloaded blob file of the question's dynamic script
# Argument 3: For Grading: JSON dictionary of params generated by the original generating script
# Argument 4: For Grading: JSON enumerated object of answers the student gave

def main():
    if len(sys.argv) <= 1:
        return
    else:
        # Note: String slicing gets the string from the start to right before the extension
        if sys.argv[2][-3:] != ".py":
            return
        question = importlib.__import__(sys.argv[2][:-3], globals(), locals(), [], 0)
        if sys.argv[1] == "--generate":
            # Prints a JSON object to the buffer of all params necessary for the question
            params = question.generate()
            print(json.dumps(params))
        elif sys.argv[1] == "--grade":
            grade = question.grade(json.loads(sys.argv[3]), json.loads(sys.argv[4]))
            # Prints a numerical value of the grade based on the JSON of student answers
            print(str(grade))
    return

if __name__ == '__main__':
    main()
